# Version: 1.0.1 (Trigger Rebuild for GPU PyTorch3D)
name: morpheus
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - cmake
  - ninja
  - gxx_linux-64=11
  - setuptools<70
  - pip
  - wheel
  - numpy<2
  - ffmpeg
  - libgl
  - mmcv==2.2.0
  - mmengine
